python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
install:
- sudo pip install --upgrade pip
- sudo pip install -r requirements.txt
# command to run tests
script:
# unit test
- pytest
