dist: "trusty"
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
install:
- sudo pip3 install --upgrade pip3 && pip3 install -r requirements.txt
# command to run tests
script:
# unit test
- pytest
