dist: "trusty"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_install:
  - chmod +x /usr/local/lib/python3.4/dist-packages/alembic

install:
- pip3 install -r requirements.txt
# command to run tests
script:
# unit test
- python -m pytest -v
