dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
install:
- sudo python3 -m pip install --upgrade pip
- sudo pip3 install -r requirements.txt
# command to run tests
script:
# unit test
- python -m pytest -v
