dist: bionic
language: python
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
install:
- sudo pip3 install -r requirements.txt
# command to run tests
script:
# unit test
- python -m pytest -v
